name: research_landscape
version: 1.0.0
profile: research_landscape
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets: ["target"]

vars:
  critical_mass_threshold: 4  # ≥4 active researchers
  recent_quarters: 8          # windows for growth/momentum

models:
  research_landscape:
    +materialized: view
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: view
