name: Nightly ETL + dbt + Export

on:
  schedule:
    # 04:17 UTC daily. Adjust as needed (America/Edmonton is UTC-6/UTC-7 depending on DST)
    - cron: '17 4 * * *'
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'etl/**'
      - 'models/**'
      - 'seeds/**'
      - 'profiles.yml'
      - 'requirements.txt'
      - '.github/workflows/etl.yml'

# Avoid overlapping runs on the same branch
concurrency:
  group: etl-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  # Required: set this as a repository **secret**
  OPENALEX_MAILTO: ${{ secrets.OPENALEX_MAILTO }}
  # Optional (Premium): set as a repository **secret** if you have one
  OPENALEX_API_KEY: ${{ secrets.OPENALEX_API_KEY }}
  # Be polite to the API (seconds between paginated requests)
  OPENALEX_RATE_SECONDS: '0.25'
  # Earliest publication date to include (YYYY-MM-DD)
  OPENALEX_START_DATE: '2015-01-01'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch OpenAlex for roster
        run: |
          python etl/fetch_openalex.py

      - name: (Optional) Convert vet taxonomy YAML → CSV seed
        if: ${{ hashFiles('data/vet_taxonomy.yaml') != '' }}
        run: |
          python etl/taxonomy_yaml_to_csv.py

      - name: dbt seed + run
        run: |
          dbt deps || true
          dbt seed --profiles-dir . --project-dir . --full-refresh
          dbt run  --profiles-dir . --project-dir .

      - name: Export CSVs for dashboard
        run: |
          python etl/export_for_dashboard.py

      - name: Upload exports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: exports
          path: exports/*.csv
