name: Nightly ETL + dbt + Export

on:
  schedule:
    # 04:17 UTC daily. Adjust as needed (America/Edmonton is UTC-6/UTC-7 depending on DST)
    - cron: '17 4 * * *'
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'etl/**'
      - 'models/**'
      - 'seeds/**'
      - 'profiles.yml'
      - 'dbt_project.yml'
      - 'requirements.txt'
      - '.github/workflows/etl.yml'

# Avoid overlapping runs on the same branch
concurrency:
  group: etl-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  # Required: set this as a repository **secret**
  OPENALEX_MAILTO: ${{ secrets.OPENALEX_MAILTO }}
  # Optional (Premium): set as a repository **secret** if you have one
  OPENALEX_API_KEY: ${{ secrets.OPENALEX_API_KEY }}
  # Be polite to the API (seconds between paginated requests)
  OPENALEX_RATE_SECONDS: '0.25'
  # Earliest publication date to include (YYYY-MM-DD)
  OPENALEX_START_DATE: '2015-01-01'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Locate dbt project directory
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          # Try common locations; otherwise search up to depth 4.
          if [ -f "dbt_project.yml" ]; then
            DBT_DIR="."
          elif [ -f "research_landscape_starter/dbt_project.yml" ]; then
            DBT_DIR="research_landscape_starter"
          else
            FOUND=$(find . -maxdepth 4 -type f -name dbt_project.yml | head -n1 || true)
            if [ -n "${FOUND}" ]; then
              DBT_DIR=$(dirname "${FOUND}")
            else
              echo "dbt_project.yml not found in repository root or subfolders." >&2
              echo "Tree preview:" >&2
              find . -maxdepth 3 -type f -name 'dbt_project.yml' -o -name 'profiles.yml' -o -name 'requirements.txt' || true
              exit 1
            fi
          fi
          echo "PROJECT_DIR=${DBT_DIR}" >> "$GITHUB_ENV"
          echo "Using PROJECT_DIR=${DBT_DIR}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch OpenAlex for roster
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          python etl/fetch_openalex.py

      - name: (Optional) Convert vet taxonomy YAML → CSV seed
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if [ -f "data/vet_taxonomy.yaml" ]; then
            python etl/taxonomy_yaml_to_csv.py
          else
            echo "No data/vet_taxonomy.yaml present; skipping"
          fi

      - name: Sanity check ETL outputs
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          ls -l data || true
          test -s data/works.csv || (echo "Missing data/works.csv — did fetch_openalex.py run?" && exit 1)
          test -s data/globals_concepts.csv || (echo "Missing data/globals_concepts.csv" && exit 1)

      - name: dbt seed + run
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          dbt deps || true
          dbt seed --profiles-dir . --project-dir . --full-refresh
          dbt run  --profiles-dir . --project-dir .

      - name: Export CSVs for dashboard
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          python etl/export_for_dashboard.py

      - name: Upload exports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: exports
          path: ${{ env.PROJECT_DIR }}/exports/*.csv
